#BUild
FROM node:14alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./frontend/*.json /app
RUN npm install 


#TEST
FROM node:14alpine as test
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY --from=builder /app/node_modules/ /app/node_modules/
COPY . . 
ENV CI=true
RUN npm test || true


#DELIVERY ARTIFACT STAGE: 
FROM node:14-alpine as delivery
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY --from=builder /app/node_modules/ /app/node_modules/
COPY . .
CMD ["npm", "start"]
