version: "3.2"
services:
 web:
   image: erikson900/todo-fe:latest
   depends_on:
     - api
   ports:
     - "3000:3000"
   networks:
     - network-backend
 api:
   image: erikson900/todo-be:latest
   depends_on:
     - mongo
   ports:
     - "3001:3001"
   networks:
     - network-backend
 mongo:
   image: mongo
   restart: always
   volumes:
     - mongodb_data:/data/db
   environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: password
   ports:
     - 27017:27017
   networks:
     - network-backend

networks:
 network-backend:

volumes:
 mongodb_data:
