version: "3.2"
services:
  web:
    image: erikson900/todo-fe:latest
    container_name: FrontEnd
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    image: erikson900/todo-be:latest
    container_name: ServerAPI
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks:
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
