# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    steps:
      - builder
      - run:
          name: Build step
          command: |
            DOCKER_BUILDKIT=1 docker build -f Dockerfile-pipeline -t someBulid:latest --target builder .
      - test     
      - run:
          name: Run Test
          command: |
            DOCKER_BUILDKIT=1 docker build -f Dockerfile-pipeline -t someTest:latest --target test .
      - setup_remote_docker:
          docker_layer_caching: true
      - delivery
      - run:
          name: Delivery stage
          command: |
            DOCKER_BUILDKIT=1 docker build -f Dockerfile-pipeline -t erikson900:latest --target delivery .
      - setup_remote_docker:
      - run:
          name: Cleanup stage
          command: yes | docker system prune
