version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: build image
          command: DOCKER_BUILDKIT=1 docker build -f Dockerfile-pipeline -t erikson900/todo-fe:latest --target builder .
  test:
    docker:
      - image: node:14-alpine
      #  auth:
      #    username: mydockerhub-user
      #    password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
